import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../../theme/tokens';

export const searchStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#eef2f7',
  },
  heroWrap: {
    height: 236,
    position: 'relative',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroFallback: {
    width: '100%',
    height: '100%',
    backgroundColor: '#d7e3f8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroMask: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  searchCard: {
    marginTop: -20,
    marginHorizontal: spacing.sm,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e3e9f2',
    backgroundColor: colors.white,
    overflow: 'hidden',
    shadowColor: '#173f85',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  locationBanner: {
    marginTop: spacing.md,
    marginHorizontal: spacing.md,
    minHeight: 38,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#d8e5ff',
    backgroundColor: '#edf4ff',
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationBannerIcon: {
    color: '#136dff',
    fontSize: 17,
    fontWeight: '700',
    marginRight: 6,
  },
  locationBannerText: {
    flex: 1,
    color: '#1b4f9f',
    fontSize: 13,
    fontWeight: '600',
  },
  locationBannerCloseBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: spacing.xs,
  },
  locationBannerCloseText: {
    color: '#7f8fa6',
    fontSize: 14,
    lineHeight: 14,
    fontWeight: '700',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
  },
  cityBlock: {
    width: 118,
  },
  cityValueRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cityTap: {
    flexShrink: 1,
    marginRight: spacing.xs,
  },
  locateAction: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locateActionIcon: {
    color: '#1570ff',
    fontSize: 30,
    lineHeight: 30,
    fontWeight: '700',
  },
  rowDivider: {
    width: 1,
    height: 44,
    backgroundColor: '#edf1f6',
    marginHorizontal: spacing.sm,
  },
  keywordBlock: {
    flex: 1,
  },
  inputLabel: {
    color: '#9ba8ba',
    fontSize: 12,
    fontWeight: '500',
  },
  cityValue: {
    color: '#162740',
    fontSize: 23,
    fontWeight: '800',
  },
  keywordInput: {
    marginTop: 2,
    color: '#1f2f47',
    fontSize: 23,
    fontWeight: '700',
    paddingVertical: 0,
  },
  dateRow: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateCell: {
    flex: 1,
  },
  dateValue: {
    color: '#1b2c45',
    fontSize: 20,
    fontWeight: '800',
  },
  dateHint: {
    marginTop: 1,
    color: '#798da7',
    fontSize: 11,
  },
  dateSeparator: {
    marginHorizontal: spacing.xs,
    color: '#cad3df',
    fontSize: 24,
  },
  nightText: {
    color: '#25344b',
    fontSize: 18,
    fontWeight: '700',
  },
  settingRow: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingCell: {
    minHeight: 30,
    justifyContent: 'center',
  },
  settingCellLeft: {
    flex: 1.25,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  settingCellRight: {
    flex: 1,
    paddingLeft: spacing.sm,
  },
  settingValue: {
    color: '#182b46',
    fontSize: 17,
    fontWeight: '700',
  },
  settingArrow: {
    color: '#405775',
    fontSize: 14,
    fontWeight: '600',
  },
  settingDivider: {
    width: 1,
    height: 24,
    backgroundColor: '#edf1f6',
  },
  settingLabel: {
    color: '#8d9eb4',
    fontSize: 15,
    fontWeight: '600',
  },
  settingSummary: {
    marginTop: 2,
    color: '#3a5377',
    fontSize: 11,
    fontWeight: '600',
  },
  tagRow: {
    marginTop: spacing.xs,
    marginHorizontal: spacing.md,
    flexDirection: 'row',
    gap: spacing.xs,
  },
  searchButtonWrap: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  searchButton: {
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  searchText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 4,
  },
  searchGlow: {
    position: 'absolute',
    right: -12,
    bottom: -16,
    width: 48,
    height: 48,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(101, 220, 255, 0.36)',
  },
  modalMaskBottom: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  calendarSheet: {
    height: '90%',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    backgroundColor: colors.white,
    overflow: 'hidden',
  },
  calendarBody: {
    flex: 1,
    minHeight: 420,
    backgroundColor: colors.white,
  },
  calendarWeekRow: {
    height: 48,
    borderTopWidth: 1,
    borderTopColor: '#edf1f6',
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  calendarWeekCell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarWeekText: {
    color: '#1a1d24',
    fontSize: 16,
    fontWeight: '600',
  },
  calendarWeekTextWeekend: {
    color: '#d34d4b',
  },
  calendarScroll: {
    flex: 1,
    backgroundColor: colors.white,
  },
  calendarScrollContent: {
    paddingBottom: spacing.sm,
  },
  calendarMonthBlock: {
    backgroundColor: colors.white,
  },
  calendarMonthHeader: {
    height: 56,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    backgroundColor: '#f3f4f6',
    borderBottomWidth: 1,
    borderBottomColor: '#eceff3',
  },
  calendarMonthTitle: {
    color: '#121212',
    fontSize: 23,
    fontWeight: '700',
  },
  calendarList: {
    backgroundColor: colors.white,
    paddingHorizontal: 4,
    paddingTop: spacing.xs,
    paddingBottom: 2,
  },
  calendarDayPressable: {
    width: '100%',
    alignItems: 'center',
  },
  calendarDayCell: {
    width: '100%',
    minHeight: 102,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 6,
    position: 'relative',
  },
  calendarDayRangeFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 8,
    bottom: 10,
    backgroundColor: '#d3e0f2',
  },
  calendarDayRangeFillMiddle: {
    left: 0,
    right: 0,
  },
  calendarDayRangeFillStart: {
    left: '50%',
    right: 0,
  },
  calendarDayRangeFillEnd: {
    left: 0,
    right: '50%',
  },
  calendarDaySelectedCard: {
    position: 'absolute',
    top: 8,
    left: 2,
    right: 2,
    bottom: 10,
    borderRadius: 10,
    backgroundColor: '#1672ff',
  },
  calendarDaySelectedOffset: {
    marginTop: 3,
  },
  calendarDayTextGroup: {
    alignItems: 'center',
  },
  calendarDayTopPlaceholder: {
    minHeight: 15,
  },
  calendarDayTopNote: {
    minHeight: 15,
    color: '#b2bac5',
    fontSize: 11,
    lineHeight: 15,
    zIndex: 2,
  },
  calendarDayTopNoteWorkday: {
    color: '#2b3546',
  },
  calendarDayTopNoteFestival: {
    color: '#b3bcc7',
  },
  calendarDayTopNoteRest: {
    color: '#b3bcc7',
  },
  calendarDayTopNoteToday: {
    color: '#7e8fa8',
  },
  calendarDayTopNoteSelected: {
    color: '#d7e7ff',
  },
  calendarDayNumber: {
    marginTop: 0,
    color: '#131f31',
    fontSize: 21,
    lineHeight: 29,
    fontWeight: '500',
    zIndex: 2,
  },
  calendarDayNumberToday: {
    color: '#cf2b22',
  },
  calendarDayNumberDisabled: {
    color: '#c1c8d3',
  },
  calendarDayNumberSelected: {
    color: colors.white,
    fontWeight: '600',
  },
  calendarDayBottomNote: {
    marginTop: -2,
    color: colors.white,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
    zIndex: 2,
  },
  calendarDoneButton: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    height: 52,
    borderRadius: 12,
    backgroundColor: '#126fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarDoneButtonDisabled: {
    backgroundColor: '#8ab7ff',
  },
  calendarDoneText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '800',
  },
  sheetHeader: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.sm,
  },
  sheetCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCloseText: {
    color: '#1f314a',
    fontSize: 26,
    lineHeight: 26,
    marginTop: -2,
  },
  sheetTitle: {
    color: '#1a2c44',
    fontSize: 18,
    fontWeight: '800',
  },
  sheetHeaderSpace: {
    width: 34,
    height: 34,
  },
  calendarModeTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginRight: 34,
  },
  calendarModeTab: {
    minWidth: 140,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  calendarModeTabActive: {
    borderBottomColor: '#1572ff',
  },
  calendarModeText: {
    color: '#1a2c44',
    fontSize: 16,
    fontWeight: '600',
  },
  calendarModeTextActive: {
    color: '#1a73ff',
    fontWeight: '800',
  },
  bottomCard: {
    backgroundColor: colors.white,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
  },
  modalTitle: {
    color: '#1c2e47',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  modalLabel: {
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    color: '#4f627f',
    fontSize: 13,
    fontWeight: '600',
  },
  bottomChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  roomGuestSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  guestTipRow: {
    marginTop: spacing.xs,
    borderRadius: radius.sm,
    backgroundColor: '#f5f8fc',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  guestTipIcon: {
    color: '#0f68ff',
    fontSize: 14,
    fontWeight: '600',
  },
  guestTipText: {
    color: '#6d7f96',
    fontSize: 14,
    fontWeight: '500',
  },
  guestCounterRow: {
    marginTop: spacing.md,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  guestCounterLabel: {
    color: '#13253f',
    fontSize: 16,
    fontWeight: '700',
  },
  guestCounterHint: {
    marginTop: 2,
    color: '#6d7f96',
    fontSize: 12,
  },
  counterActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  counterButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#1d77ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterButtonDisabled: {
    borderColor: '#d5dee9',
  },
  counterButtonText: {
    color: '#1d77ff',
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '500',
  },
  counterButtonTextDisabled: {
    color: '#d1d9e4',
  },
  counterValue: {
    width: 28,
    textAlign: 'center',
    color: '#122944',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '700',
  },
  guestDoneButton: {
    marginTop: spacing.lg,
    height: 52,
    borderRadius: 12,
    backgroundColor: '#136eff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guestDoneText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '800',
  },
  filterSheet: {
    maxHeight: '82%',
    backgroundColor: colors.white,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  filterScroll: {
    marginTop: spacing.xs,
  },
  filterSectionTitle: {
    color: '#1a2b43',
    fontSize: 17,
    fontWeight: '800',
  },
  sliderTrack: {
    marginTop: spacing.sm,
    marginBottom: spacing.md,
    width: '88%',
    alignSelf: 'center',
    height: 32,
    justifyContent: 'center',
  },
  sliderTrackBase: {
    height: 6,
    borderRadius: radius.pill,
    backgroundColor: '#d4e4ff',
  },
  sliderTrackActive: {
    position: 'absolute',
    top: 13,
    height: 6,
    borderRadius: radius.pill,
    backgroundColor: '#1874ff',
  },
  sliderThumb: {
    position: 'absolute',
    top: 2,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#1874ff',
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sliderThumbText: {
    color: '#1874ff',
    fontSize: 13,
    lineHeight: 13,
    fontWeight: '600',
  },
  priceInputsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  priceField: {
    flex: 1,
    borderRadius: radius.sm,
    backgroundColor: '#f7f8fa',
    borderWidth: 1,
    borderColor: '#e3e8ef',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  priceFieldLabel: {
    color: '#8f9fb3',
    fontSize: 13,
    fontWeight: '600',
  },
  priceInputLine: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pricePrefix: {
    color: '#182b46',
    fontSize: 16,
    fontWeight: '700',
  },
  priceFieldInput: {
    flex: 1,
    color: '#182b46',
    fontSize: 16,
    fontWeight: '700',
    paddingVertical: 0,
    marginLeft: 2,
  },
  priceFieldDash: {
    color: '#a1afbf',
    fontSize: 20,
    fontWeight: '700',
  },
  presetGrid: {
    marginTop: spacing.md,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  presetChip: {
    width: '30%',
    minHeight: 44,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: '#edf1f6',
    backgroundColor: '#f6f8fb',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  presetChipActive: {
    borderColor: '#b6d2ff',
    backgroundColor: '#eaf2ff',
  },
  presetChipText: {
    color: '#324a70',
    fontSize: 14,
    fontWeight: '600',
  },
  presetChipTextActive: {
    color: '#176fff',
    fontWeight: '700',
  },
  starTitleRow: {
    marginTop: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  starGrid: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  starCard: {
    width: '30%',
    minHeight: 72,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: '#edf1f6',
    backgroundColor: '#f6f8fb',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  starCardActive: {
    borderColor: '#b6d2ff',
    backgroundColor: '#eaf2ff',
  },
  starCardTitle: {
    color: '#1d2f47',
    fontSize: 15,
    fontWeight: '700',
  },
  starCardTitleActive: {
    color: '#176fff',
  },
  starCardDesc: {
    marginTop: 2,
    color: '#7d8da2',
    fontSize: 12,
    fontWeight: '500',
  },
  starCardDescActive: {
    color: '#3d79d8',
  },
  filterFooter: {
    marginTop: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  footerBtn: {
    flex: 1,
    height: 50,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBtnLight: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#ced9e8',
  },
  footerBtnPrimary: {
    backgroundColor: '#156fff',
  },
  footerBtnLightText: {
    color: '#2a3d59',
    fontSize: 16,
    fontWeight: '700',
  },
  footerBtnPrimaryText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '800',
  },
  singleButton: {
    marginTop: spacing.md,
    height: 40,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#edf4ff',
  },
  singleButtonText: {
    color: '#325584',
    fontWeight: '700',
  },
});
