import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../../theme/tokens';

export const hotelListStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#f4f6f9',
    position: 'relative',
  },
  topSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
  },
  backButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: {
    color: '#1b2a42',
    fontSize: 24,
    lineHeight: 24,
    marginTop: -2,
  },
  leftSearchCard: {
    marginLeft: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: '#f5f7fa',
    borderWidth: 1,
    borderColor: '#ecf1f6',
    paddingHorizontal: spacing.xs,
    paddingVertical: 0,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  cityText: {
    color: '#152740',
    fontSize: 16,
    fontWeight: '800',
  },
  dateText: {
    color: '#263954',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
  },
  searchCardActive: {
    borderColor: '#d1e2ff',
    backgroundColor: '#edf4ff',
  },
  rightSearchCard: {
    flex: 1,
    marginLeft: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: '#f5f7fa',
    borderWidth: 1,
    borderColor: '#ecf1f6',
    paddingHorizontal: spacing.sm,
    paddingVertical: 0,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rightSearchInput: {
    flex: 1,
    color: '#2e3f59',
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 0,
  },
  keywordClearButton: {
    marginLeft: spacing.xs,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#d8dde8',
  },
  keywordClearText: {
    color: '#ffffff',
    fontSize: 11,
    lineHeight: 11,
    fontWeight: '700',
  },
  sortBar: {
    backgroundColor: colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: '#eef2f7',
  },
  sortItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    minHeight: 28,
  },
  sortText: {
    color: '#1f2f47',
    fontSize: 14,
    fontWeight: '700',
  },
  sortTextActive: {
    color: '#1f68ff',
  },
  quickTagScroll: {
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#eef2f7',
    flexGrow: 0,
  },
  quickTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  listContent: {
    paddingBottom: spacing.xxl,
    paddingTop: 2,
  },
  noMoreText: {
    textAlign: 'center',
    color: '#788aa2',
    marginVertical: spacing.lg,
    fontSize: 12,
  },
  dropdownLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
  },
  dropdownBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  dropdownCardBase: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    overflow: 'hidden',
    borderTopWidth: 1,
    borderTopColor: '#edf1f6',
  },
  searchPanelCard: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  searchPanelLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
  },
  searchPanelLocationText: {
    flex: 1,
    color: '#0e1f3e',
    fontSize: 21,
    fontWeight: '800',
    marginRight: spacing.sm,
  },
  searchPanelLocateButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchPanelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
  },
  searchPanelPrimaryText: {
    color: '#112746',
    fontSize: 16,
    fontWeight: '700',
  },
  searchPanelNightText: {
    color: '#112746',
    fontSize: 16,
    fontWeight: '700',
  },
  searchPanelLocateIcon: {
    color: '#1570ff',
    fontSize: 24,
    fontWeight: '700',
  },
  searchPanelRowLabel: {
    color: '#7b8fa8',
    fontSize: 14,
    fontWeight: '500',
  },
  searchPanelRowValue: {
    color: '#112746',
    fontSize: 16,
    fontWeight: '700',
  },
  searchPanelConfirmButton: {
    marginTop: spacing.md,
    height: 46,
    borderRadius: radius.md,
    backgroundColor: colors.brandBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchPanelConfirmText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '700',
  },
  sortDropdownCard: {
    maxHeight: '65%',
  },
  sortOptionRow: {
    minHeight: 52,
    paddingHorizontal: spacing.md,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eef2f7',
  },
  sortOptionRowCompact: {
    minHeight: 54,
  },
  sortOptionTitle: {
    color: '#1b2a42',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  sortOptionTitleActive: {
    color: colors.brandBlue,
    fontWeight: '700',
  },
  sortOptionDesc: {
    color: '#9bacbf',
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
  },
  sortCheckMark: {
    position: 'absolute',
    right: spacing.md,
    top: '50%',
    marginTop: -10,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.brandBlue,
    color: colors.white,
    textAlign: 'center',
    lineHeight: 20,
    fontSize: 13,
    fontWeight: '700',
  },
  filterDropdownCard: {
    maxHeight: '78%',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  dropdownScrollContainer: {
    flexShrink: 1,
  },
  modalScrollContent: {
    paddingBottom: spacing.sm,
  },
  modalTitle: {
    color: '#1c2e47',
    fontSize: 17,
    fontWeight: '700',
  },
  modalLabel: {
    marginTop: spacing.md,
    marginBottom: spacing.xs,
    color: '#435772',
    fontWeight: '600',
    fontSize: 13,
  },
  tagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  input: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#dce7fa',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    color: colors.ink900,
    backgroundColor: '#f5f9ff',
  },
  priceInput: {
    flex: 1,
  },
  separator: {
    color: colors.ink500,
    fontWeight: '700',
  },
  modalActions: {
    marginTop: spacing.xl,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  modalButton: {
    flex: 1,
    height: 44,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#edf4ff',
  },
  confirmButton: {
    backgroundColor: '#0f6dff',
  },
  cancelText: {
    color: colors.ink700,
    fontWeight: '600',
  },
  confirmText: {
    color: colors.white,
    fontWeight: '700',
  },
});
