import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../../theme/tokens';

export const hotelDetailStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#edf1f6',
  },
  listContent: {
    backgroundColor: '#edf1f6',
    paddingBottom: 96,
  },
  heroWrap: {
    position: 'relative',
  },
  bannerImage: {
    width: '100%',
    height: 270,
    backgroundColor: '#dbe9ff',
  },
  bannerImageFallback: {
    width: '100%',
    height: 270,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e8efff',
  },
  bannerFallbackText: {
    color: '#607d9f',
    fontSize: 13,
  },
  heroMask: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 270,
  },
  topActions: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    top: spacing.sm,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(14,24,40,0.46)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBack: {
    color: colors.white,
    fontSize: 34,
    lineHeight: 34,
    marginTop: -2,
  },
  previewCountBadge: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.xl,
    minWidth: 52,
    height: 28,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(18, 28, 44, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
  },
  previewCountText: {
    color: colors.white,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '700',
  },
  mainCard: {
    marginTop: -20,
    marginHorizontal: spacing.sm,
    borderRadius: 20,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  hotelName: {
    flex: 1,
    color: '#14253e',
    fontSize: 23,
    lineHeight: 31,
    fontWeight: '800',
  },
  diamond: {
    color: '#f2a523',
    fontSize: 9,
    letterSpacing: 0.8,
  },
  badgeRow: {
    marginTop: spacing.xs,
    flexDirection: 'row',
    gap: spacing.xs,
  },
  smallBadge: {
    borderRadius: radius.sm,
    backgroundColor: '#f5efe2',
    paddingHorizontal: spacing.xs,
    paddingVertical: 4,
  },
  smallBadgeText: {
    color: '#8a6b32',
    fontSize: 11,
    fontWeight: '600',
  },
  facilityRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  facilityChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: radius.pill,
    backgroundColor: '#f4f7fb',
    borderWidth: 1,
    borderColor: '#e7edf6',
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  facilityLabel: {
    color: '#304e76',
    fontSize: 13,
    fontWeight: '600',
  },
  facilitySummary: {
    alignSelf: 'center',
  },
  facilityMoreText: {
    color: '#6b7f9d',
    fontSize: 12,
    fontWeight: '600',
  },
  reviewCardRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    gap: spacing.xs,
  },
  reviewCard: {
    flex: 1,
    borderRadius: radius.sm,
    backgroundColor: '#edf5ff',
    padding: spacing.xs,
  },
  reviewCardFull: {
    flex: 1,
  },
  reviewTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  scoreBadge: {
    borderRadius: 4,
    backgroundColor: '#1f68ff',
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  scoreText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '800',
  },
  reviewTopText: {
    color: '#2e4f79',
    fontSize: 12,
    fontWeight: '600',
  },
  realInfoPrimary: {
    marginTop: 6,
    color: '#1f2f46',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 24,
  },
  realInfoSecondary: {
    marginTop: 4,
    color: '#567194',
    fontSize: 13,
    lineHeight: 18,
  },
  reviewQuote: {
    marginTop: 6,
    color: '#1f2f46',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  mapCard: {
    flex: 1,
    borderRadius: radius.sm,
    backgroundColor: '#eff7f7',
    padding: spacing.xs,
  },
  mapCardDisabled: {
    opacity: 0.7,
  },
  mapDistance: {
    color: '#1f2f46',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  mapAddress: {
    marginTop: 4,
    color: '#425b7d',
    fontSize: 13,
  },
  mapLink: {
    marginTop: spacing.xs,
    color: '#3a567f',
    fontSize: 13,
    fontWeight: '700',
  },
  datePanel: {
    marginTop: spacing.md,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: '#e5ebf3',
    backgroundColor: '#fbfcfe',
    padding: spacing.xs,
  },
  dateEditorRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateEditorLeft: {
    flex: 1,
    minHeight: 54,
    justifyContent: 'center',
  },
  dateMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  dateHintLabel: {
    color: '#374d70',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  dateText: {
    color: '#162740',
    fontSize: 18,
    fontWeight: '800',
  },
  dateEditorDivider: {
    width: 1,
    height: 48,
    backgroundColor: '#edf1f6',
    marginHorizontal: spacing.sm,
  },
  guestEditorRight: {
    width: 130,
    minHeight: 54,
    justifyContent: 'center',
  },
  guestEditorLabel: {
    color: '#6d7f96',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  guestEditorValueRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  guestEditorValue: {
    color: '#13253f',
    fontSize: 18,
    fontWeight: '700',
  },
  bottomTagRow: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    gap: 5,
    flexWrap: 'wrap',
  },
  bottomTag: {
    borderRadius: radius.sm,
    backgroundColor: '#f3f5f9',
    paddingHorizontal: spacing.xs,
    paddingVertical: 5,
  },
  bottomTagText: {
    color: '#4d627e',
    fontSize: 11,
    fontWeight: '600',
  },
  sectionTitle: {
    marginTop: spacing.md,
    color: '#1f2f47',
    fontSize: 19,
    fontWeight: '800',
  },
  footerSpace: {
    height: spacing.xxl,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#e5ebf3',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  askButton: {
    width: 64,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  askIcon: {
    color: '#1f68ff',
    fontSize: 24,
    lineHeight: 24,
    fontWeight: '700',
  },
  askText: {
    color: '#2e466b',
    fontSize: 12,
    fontWeight: '600',
  },
  priceWrap: {
    flex: 1,
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  selectionSummary: {
    color: '#586d88',
    fontSize: 12,
    fontWeight: '600',
  },
  priceRowCompact: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  selectionHint: {
    marginTop: 1,
    color: '#7085a0',
    fontSize: 11,
    fontWeight: '500',
  },
  bottomPrice: {
    color: '#1f68ff',
    fontSize: 30,
    lineHeight: 30,
    fontWeight: '800',
  },
  bottomPriceSuffix: {
    color: '#1f68ff',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 3,
  },
  mainButton: {
    marginLeft: 'auto',
    height: 48,
    borderRadius: 12,
    backgroundColor: '#1472ff',
    paddingHorizontal: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainButtonDisabled: {
    backgroundColor: '#8fb8ff',
  },
  mainButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '800',
  },
});
